# version: 2

# models:
#   - name: fct_revenue_summary
#     description: Aggregated daily revenue and booking metrics per flight.
#     columns:
#       - name: flight_day
#         tests: [not_null]
#       - name: total_revenue_usd
#       - name: confirmed_bookings
#       - name: cancelled_bookings
#       - name: flight_count

#   - name: fct_operational_costs
#     description: Estimated daily operational cost per flight based on crew, fuel, and aircraft data.
#     columns:
#       - name: flight_id
#         tests: [not_null]
#       - name: flight_day
#         tests: [not_null]
#       - name: total_crew_cost
#       - name: estimated_fuel_cost
#       - name: aircraft_status
#       - name: total_operational_cost

#   - name: fct_flight_profit
#     description: Daily profit summary by combining revenue and operational costs per flight_day.
#     columns:
#       - name: flight_day
#         tests: [not_null]
#       - name: flight_count
#       - name: total_revenue_usd
#       - name: total_operational_cost
#       - name: net_profit_usd
