version: 2
models:
- name: int_flights_metrics
  columns: []
- name: int_flight_revenue
  columns: []
# - name: int_crew_metrics
#   columns: []
# - name: int_supplier_metrics
#   columns: []
# - name: int_revenue_details
#   columns: []
# - name: int_ontime_events
#   columns: []
